name: Pull Request Build and Deploy

on:
  pull_request:
    branches: [ main, integration ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      pr_number:
        description: Number of the Pull Request
        required: true
  
# Environment variables
env:
  DEPLOY_REPO_NAME: zhaostephen.com-2021-static-pr${{ github.event.pull_request.number || github.event.inputs.pr_number }}
  PR_MERGE_BRANCH: refs/pull/${{ github.event.pull_request.number || github.event.inputs.pr_number }}/merge

jobs:
  create-page-host:
    runs-on: ubuntu-latest
    steps:
      - name: Create new repository for temporary deployment
        uses: octobay/create-repository-action@v1
        with:
          name: ${{ env.DEPLOY_REPO_NAME }}
          org: zhaostephencom-ghp
          access-token: ${{ secrets.PAT }}

  pr-build-deploy:
    needs: create-page-host
    runs-on: ubuntu-latest
    environment:
      name: pr-staging
      url: https://zhaostephencom-ghp.github.io/${{ env.DEPLOY_REPO_NAME }}/
      
    steps:
      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Checkout PR repository
        uses: actions/checkout@v2
        with:
          path: 'pr-build'
          ref: ${{ env.PR_MERGE_BRANCH }}

      - name: Checkout deployment repository
        uses: actions/checkout@v2
        with:
          repository: zhaostephencom-ghp/${{ env.DEPLOY_REPO_NAME }}
          path: 'pr-deploy'
          token: ${{ secrets.PAT }}

      - name: Deploy to deployment repository
        run: |
          cp -r pr-build/* pr-deploy/
          cd pr-deploy
          touch .nojekyll
          git add .
          git commit -m $GITHUB_SHA

          # Archive to commit-specific branch
          git checkout -b commit/$GITHUB_SHA
          git push -u origin commit/$GITHUB_SHA

          # Publish to gh-pages branch
          git checkout -b gh-pages
          git push -uf origin gh-pages
