name: Build and Deploy to Dev
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      PUBLIC_URL__override:
        description: Override for env var PUBLIC_URL 
        required: false

env:
  PUBLIC_URL: ${{ github.event.inputs.PUBLIC_URL__override || secrets.PUBLIC_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://${{ env.PUBLIC_URL }}
    steps:
      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: 'build'
      
      - name: Build
        run: |
          cd build
          # Do build stuff here
          cd ..
      
      - name: Checkout Dev Target
        uses: actions/checkout@v2
        with:
          repository: zhaostephencom-ghp/zhaostephen.com-dev
          path: 'deploy'
          token: ${{ secrets.PAT }}
      
      - name: Push files to target
        run: |
          cp -r build/* deploy
          cd deploy
          touch .nojekyll
          # Do not do CNAME because the PUBLIC_URL here is just a github.io page
          # echo ${{ env.PUBLIC_URL }} > CNAME
          git add .
          git commit -m $GITHUB_SHA
          git push